### ISSUE TITLE
Cannot navigate to a page without reloading or directly typing the URL

### ISSUE THREAD

**Issue by andrewhong04** [rutgersesports/rutgersesports.club#12]
## Summary
There is a fatal flaw where users cannot navigate to a page without reloading or directly typing the URL. This is an issue since it is optimal to advertise stuff like https://rutgersesports.club/apply for quick access.
A way around this is to manually navigate from the homepage to the apply page, which is not good.

This requires rewriting the entire project, so I do not want anyone other than me to be working on this. I'll be working on this issue during a weekend.

## Todo List
 - [ ] Integrate webpack to the project
 - [ ] Convert necessary files to TypeScript
 - [ ] Follow this project: https://github.com/rafgraph/spa-github-pages

**Comment by andrewhong04** [comment]
Fixed: https://github.com/rutgersesports/rutgersesports.club/commit/6c030e6add28b4d31c11d8db7dbf27d909bf0484

Not the ideal solution though.
